# Generated by Django 3.0.3 on 2020-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaintenanceRequestApp', '0003_auto_20200219_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('badge_number', models.IntegerField()),
                ('department', models.IntegerField()),
                ('authorized_supervisor', models.CharField(max_length=200)),
                ('equipment_number', models.CharField(max_length=200)),
                ('equipment_name', models.CharField(max_length=200)),
                ('equipment_location', models.CharField(max_length=200)),
                ('equipment_problem', models.CharField(max_length=200)),
                ('explain_problem', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
